### ISSUE TITLE
config.yaml question

### ISSUE THREAD

**Issue by svshepherd** [madhan001/lfmxtractplus-examples#1]
first, thanks for your work on this -- I've built a similar notebook but was dismayed by the challenge of integrating spotify data; i'm eager to see how your approach compares. 

what should I be using in place of 'C:\\Users\Madhan\PycharmProjects\lfm4pandas\config.yaml' ?

**Comment by madhan001** [comment]
Sorry for the delayed response, config.yaml needs the spotify and lastfm developer keys. You can find more information here https://github.com/madhan001/lfmxtractplus#configyaml
